oc_plateform_homepage:
    path:     /
    defaults: { _controller: OCPlateformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlateformBundle:Advert:index }
